version: '3.8'

services:
  mongodb:
    container_name: mongodb-products
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_products:/data/db
  
  postgres_cart:
    container_name: postgres_cart
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres_cart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    volumes:
      - postgres_cart:/postgresql/data
    
volumes:
  mongodb_products:
  postgres_cart:
